#pragma once

// ===========================================================================
// kiou_rva_1_1_0.h — site addresses for KIOU 1.1.0 (CFBundleVersion 15).
//
// GENERATED by tools/gen_rva_header.py from recipes/v1_1_0.py and the
// direct-ABI anchors it carries. Do not hand-edit: fix the recipe (or the
// anchor) and regenerate. tools/check_recipes.py re-checks every hook-site
// value against the recipe on each run.
// ===========================================================================

#define KIOU_HOOK_OBSERVER_SLOT_RVA        0x0A516468
#define KIOU_HOOK_ENTRY_SLOT_BASE_RVA      0x0A516268

// CAVE_REGION[0] from recipes/v1_1_0.py — the consumer's Makefile may
// override this, but the two must agree.
#ifndef KIOU_HOOK_CAVE_REGION_START
#define KIOU_HOOK_CAVE_REGION_START        0x94B8024
#endif


#define KIOU_HOOK_RVA_SET_TARGET_FRAMERATE                  0x7A9A020
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE                       0x6C58720
#define KIOU_HOOK_RVA_NSS_SETSKILLEVEL                      0x6C5B64C
#define KIOU_HOOK_RVA_NSS_SEARCHFULL                        0x6C5B6E4
#define KIOU_HOOK_RVA_ACCOUNT_EXISTS                        0x682FF8C
#define KIOU_HOOK_RVA_LOGIN_ARGS_CREATE                     0x6AB29B0
#define KIOU_HOOK_RVA_REGISTER_USER_ARGS_CREATE             0x6AB2A5C
#define KIOU_HOOK_RVA_RUN_LOGIN_SEQ_MOVENEXT                0x66CED7C
#define KIOU_HOOK_RVA_GET_SELF_PROFILE_MOVENEXT             0x6ACF014
#define KIOU_HOOK_RVA_HTTPMSGINVOKER_SEND_ASYNC             0x6FA5DDC
#define KIOU_HOOK_RVA_AI_END                                0x68F4988
#define KIOU_HOOK_RVA_CPUSTREAM_END                         0x68FCD78
#define KIOU_HOOK_RVA_LOCAL_END                             0x69103D4
#define KIOU_HOOK_RVA_ONLINE_END                            0x6911E8C
#define KIOU_HOOK_RVA_REPLAY_END                            0x693DE6C
#define KIOU_HOOK_RVA_HEADER_PROVIDER_SET_OR_UPDATE_HEADER  0x6AEF65C
#define KIOU_HOOK_RVA_SYNC_ITEM_LIST_MERGE                  0x6B58E3C
#define KIOU_HOOK_RVA_COLLECTION_PRESET_MERGE               0x6B625EC
#define KIOU_HOOK_RVA_SELECT_CHAR_ASYNC                     0x6BCBFA8
#define KIOU_HOOK_RVA_SELECT_CHAR_REPLY_MERGE               0x6B48BD4
#define KIOU_HOOK_RVA_MATCHING_PLAYER_MERGE                 0x6A61C94
#define KIOU_HOOK_RVA_HISTORY_DETAIL_MERGE                  0x6B22EE0
#define KIOU_HOOK_RVA_HISTORY_GET_PREMIUM                   0x6B22940
#define KIOU_HOOK_RVA_KIFU_DETAIL_IS_PREMIUM                0x6756674
#define KIOU_HOOK_RVA_VOICE_PLAYER_SATISFIES                0x6722C4C
#define KIOU_HOOK_RVA_VOICE_CELL_GET_IS_LOCKED              0x6741F94
#define KIOU_HOOK_RVA_BSE_CTOR                              0x6888898
#define KIOU_HOOK_RVA_BSE_ENSURE_INITIALIZED                0x0
#define KIOU_HOOK_RVA_RBSUPPORT_GET_ENABLED                 0x684C374
#define KIOU_HOOK_RVA_RBSUPPORT_GET_DEPTH                   0x684C394
#define KIOU_HOOK_RVA_HOME_UTILITY_PRESENTER_CTOR           0x69A5A70
#define KIOU_HOOK_RVA_UIBUTTONBASE_ONPOINTERCLICK           0x6CFB5C4
#define KIOU_HOOK_RVA_TITLE_SCENE_MOVENEXT                  0x6CF5EF4
#define KIOU_HOOK_RVA_GAME_ORCHESTRATOR_IS_AFK              0x6854064
#define KIOU_HOOK_RVA_BSE_EVALUATE_ASYNC                    0x6888A9C
#define KIOU_HOOK_RVA_MOVE_RESULT_CAN_USE_SPECIAL           0x6A650DC
#define KIOU_HOOK_RVA_MOVE_RESULT_FREE_REMAINING            0x6A650AC
#define KIOU_HOOK_RVA_MOVE_RESULT_TICKET_REMAINING          0x6A650BC
#define KIOU_HOOK_RVA_MP_FREE_REMAINING                     0x6A60ECC
#define KIOU_HOOK_RVA_MP_PAID_AVAILABLE                     0x6A60EDC
#define KIOU_HOOK_RVA_MATCH_GET_VALID_FOUND                 0x6C23BF0
#define KIOU_HOOK_RVA_MATCH_RECEIVE_TIMEOUT_MOVENEXT        0x6C2586C
#define KIOU_HOOK_RVA_MATCH_STREAM_ARGS_CREATE              0x6AE500C
#define KIOU_HOOK_RVA_MATCH_START_D3_MOVENEXT               0x6C26EF0
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_SEND_ASYNC       0x6AE5820
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_DISPOSE_ASYNC    0x6AE5634
#define KIOU_HOOK_RVA_MSG_EXT_TO_BYTE_ARRAY                 0x617A650
#define KIOU_HOOK_RVA_MSG_EXT_WRITE_TO_BUFFER               0x617ACEC
#define KIOU_HOOK_RVA_MSG_EXT_MERGE_FROM_ROSEQ              0x617A360
#define KIOU_HOOK_RVA_MSG_PARSER_MERGE_FROM_CODED           0x617BA4C
#define KIOU_HOOK_RVA_NSS_SEARCH                            0x6C5B6C0
#define KIOU_HOOK_RVA_NSS_SEARCHMULTI                       0x6C5C090
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPV                     0x6C5CD8C
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIWITHPV                 0x6C5D2F8
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPVWITHPV               0x6C59AFC
#define KIOU_HOOK_RVA_NSS_SETOPTION                         0x6C57848
#define KIOU_HOOK_RVA_BACK_TO_TITLE_RUN_ASYNC               0x6C1581C
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE_DIRECT                0x6C58720
#define KIOU_HOOK_RVA_NSS_SETOPTION_DIRECT                  0x6C57848
#define KIOU_HOOK_RVA_GAMEOBJECT_GETCOMPONENT               0x7AF8F74
#define KIOU_HOOK_RVA_RTU_WORLDTOSCREENPOINT                0x7E52670
#define KIOU_HOOK_RVA_JSON_FORMATTER_GET_DEFAULT            0x6166B74
#define KIOU_HOOK_RVA_JSON_FORMATTER_FORMAT                 0x616875C
#define KIOU_HOOK_RVA_GAMECTRL_GET_USI_TEXT                 0x6C6DA6C
#define KIOU_HOOK_RVA_POSITION_TO_SFEN                      0x6C6DD6C
#define KIOU_HOOK_RVA_USIPARSER_PARSE_USI                   0x6C84A50
#define KIOU_HOOK_RVA_KIFWRITEOPTIONS_CTOR                  0x6C81060
#define KIOU_HOOK_RVA_KIFWRITER_WRITE                       0x6C81068
#define KIOU_HOOK_RVA_RUN_RESET_USER_DATA_SEQ               0x6CEF708
#define KIOU_HOOK_RVA_RUN_DELETE_ACCOUNT_SEQ                0x6CEF7B8
