#pragma once

// ===========================================================================
// kiou_rva_1_0_1.h — site addresses for KIOU 1.0.1 (CFBundleVersion 11).
//
// GENERATED by tools/gen_rva_header.py from recipes/v1_0_1.py and the
// direct-ABI anchors it carries. Do not hand-edit: fix the recipe (or the
// anchor) and regenerate. tools/check_recipes.py re-checks every hook-site
// value against the recipe on each run.
// ===========================================================================

#define KIOU_HOOK_OBSERVER_SLOT_RVA        0x091E93B8
#define KIOU_HOOK_ENTRY_SLOT_BASE_RVA      0x091E91B8

// CAVE_REGION[0] from recipes/v1_0_1.py — the consumer's Makefile may
// override this, but the two must agree.
#ifndef KIOU_HOOK_CAVE_REGION_START
#define KIOU_HOOK_CAVE_REGION_START        0x8268024
#endif


#define KIOU_HOOK_RVA_SET_TARGET_FRAMERATE                  0x6B6B758
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE                       0x5D320E0
#define KIOU_HOOK_RVA_NSS_SETSKILLEVEL                      0x5D3206C
#define KIOU_HOOK_RVA_NSS_SEARCHFULL                        0x5D32178
#define KIOU_HOOK_RVA_ACCOUNT_EXISTS                        0x591E860
#define KIOU_HOOK_RVA_LOGIN_ARGS_CREATE                     0x5B9899C
#define KIOU_HOOK_RVA_REGISTER_USER_ARGS_CREATE             0x5B98A2C
#define KIOU_HOOK_RVA_RUN_LOGIN_SEQ_MOVENEXT                0x5812534
#define KIOU_HOOK_RVA_GET_SELF_PROFILE_MOVENEXT             0x5BB4774
#define KIOU_HOOK_RVA_HTTPMSGINVOKER_SEND_ASYNC             0x607C974
#define KIOU_HOOK_RVA_AI_END                                0x59E5958
#define KIOU_HOOK_RVA_CPUSTREAM_END                         0x59EC818
#define KIOU_HOOK_RVA_LOCAL_END                             0x59FF8F8
#define KIOU_HOOK_RVA_ONLINE_END                            0x5A0139C
#define KIOU_HOOK_RVA_REPLAY_END                            0x5A2B564
#define KIOU_HOOK_RVA_HEADER_PROVIDER_SET_OR_UPDATE_HEADER  0x5BD4C80
#define KIOU_HOOK_RVA_SYNC_ITEM_LIST_MERGE                  0x5C37034
#define KIOU_HOOK_RVA_COLLECTION_PRESET_MERGE               0x5C4065C
#define KIOU_HOOK_RVA_SELECT_CHAR_ASYNC                     0x5CA7C90
#define KIOU_HOOK_RVA_SELECT_CHAR_REPLY_MERGE               0x5C26DCC
#define KIOU_HOOK_RVA_MATCHING_PLAYER_MERGE                 0x5B4CAEC
#define KIOU_HOOK_RVA_HISTORY_DETAIL_MERGE                  0x5C01328
#define KIOU_HOOK_RVA_HISTORY_GET_PREMIUM                   0x5C00D88
#define KIOU_HOOK_RVA_KIFU_DETAIL_IS_PREMIUM                0x585B25C
#define KIOU_HOOK_RVA_VOICE_PLAYER_SATISFIES                0x582B88C
#define KIOU_HOOK_RVA_VOICE_CELL_GET_IS_LOCKED              0x584ADC0
#define KIOU_HOOK_RVA_BSE_CTOR                              0x597A448
#define KIOU_HOOK_RVA_BSE_ENSURE_INITIALIZED                0x597BAFC
#define KIOU_HOOK_RVA_RBSUPPORT_GET_ENABLED                 0x593E630
#define KIOU_HOOK_RVA_RBSUPPORT_GET_DEPTH                   0x593E650
#define KIOU_HOOK_RVA_HOME_UTILITY_PRESENTER_CTOR           0x5A9F298
#define KIOU_HOOK_RVA_UIBUTTONBASE_ONPOINTERCLICK           0x5DD1E08
#define KIOU_HOOK_RVA_TITLE_SCENE_MOVENEXT                  0x5DCC728
#define KIOU_HOOK_RVA_GAME_ORCHESTRATOR_IS_AFK              0x59455D4
#define KIOU_HOOK_RVA_BSE_EVALUATE_ASYNC                    0x597B570
#define KIOU_HOOK_RVA_MOVE_RESULT_CAN_USE_SPECIAL           0x5B4FE18
#define KIOU_HOOK_RVA_MOVE_RESULT_FREE_REMAINING            0x5B4FDE8
#define KIOU_HOOK_RVA_MOVE_RESULT_TICKET_REMAINING          0x5B4FDF8
#define KIOU_HOOK_RVA_MP_FREE_REMAINING                     0x5B4BC54
#define KIOU_HOOK_RVA_MP_PAID_AVAILABLE                     0x5B4BC64
#define KIOU_HOOK_RVA_MATCH_GET_VALID_FOUND                 0x5D04E94
#define KIOU_HOOK_RVA_MATCH_RECEIVE_TIMEOUT_MOVENEXT        0x5D06B10
#define KIOU_HOOK_RVA_MATCH_STREAM_ARGS_CREATE              0x5BCA664
#define KIOU_HOOK_RVA_MATCH_START_D3_MOVENEXT               0x5D08194
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_SEND_ASYNC       0x5BCAE78
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_DISPOSE_ASYNC    0x5BCAC8C
#define KIOU_HOOK_RVA_MSG_EXT_TO_BYTE_ARRAY                 0x52BDBEC
#define KIOU_HOOK_RVA_MSG_EXT_WRITE_TO_BUFFER               0x52BE288
#define KIOU_HOOK_RVA_MSG_EXT_MERGE_FROM_ROSEQ              0x52BD8FC
#define KIOU_HOOK_RVA_MSG_PARSER_MERGE_FROM_CODED           0x52BEFE8
#define KIOU_HOOK_RVA_NSS_SEARCH                            0x5D32154
#define KIOU_HOOK_RVA_NSS_SEARCHMULTI                       0x5D32AA8
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPV                     0x5D337A4
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIWITHPV                 0x5D33D10
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPVWITHPV               0x5D34A90
#define KIOU_HOOK_RVA_NSS_SETOPTION                         0x5D31D98
#define KIOU_HOOK_RVA_BACK_TO_TITLE_RUN_ASYNC               0x5CF712C
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE_DIRECT                0x5D320E0
#define KIOU_HOOK_RVA_NSS_SETOPTION_DIRECT                  0x5D31D98
#define KIOU_HOOK_RVA_GAMEOBJECT_GETCOMPONENT               0x6BCA6AC
#define KIOU_HOOK_RVA_RTU_WORLDTOSCREENPOINT                0x6F20040
#define KIOU_HOOK_RVA_JSON_FORMATTER_GET_DEFAULT            0x52AA110
#define KIOU_HOOK_RVA_JSON_FORMATTER_FORMAT                 0x52ABCF8
#define KIOU_HOOK_RVA_GAMECTRL_GET_USI_TEXT                 0x5D44074
#define KIOU_HOOK_RVA_POSITION_TO_SFEN                      0x5D44374
#define KIOU_HOOK_RVA_USIPARSER_PARSE_USI                   0x5D572B4
#define KIOU_HOOK_RVA_KIFWRITEOPTIONS_CTOR                  0x5D53960
#define KIOU_HOOK_RVA_KIFWRITER_WRITE                       0x5D53968
#define KIOU_HOOK_RVA_RUN_RESET_USER_DATA_SEQ               0x5DC6908
#define KIOU_HOOK_RVA_RUN_DELETE_ACCOUNT_SEQ                0x5DC69B8
