#pragma once

// ===========================================================================
// kiou_rva_1_0_2.h — site addresses for KIOU 1.0.2 (CFBundleVersion 12).
//
// GENERATED by tools/gen_rva_header.py from recipes/v1_0_2.py and the
// direct-ABI anchors it carries. Do not hand-edit: fix the recipe (or the
// anchor) and regenerate. tools/check_recipes.py re-checks every hook-site
// value against the recipe on each run.
// ===========================================================================

#define KIOU_HOOK_OBSERVER_SLOT_RVA        0x091E93B8
#define KIOU_HOOK_ENTRY_SLOT_BASE_RVA      0x091E91B8

// CAVE_REGION[0] from recipes/v1_0_2.py — the consumer's Makefile may
// override this, but the two must agree.
#ifndef KIOU_HOOK_CAVE_REGION_START
#define KIOU_HOOK_CAVE_REGION_START        0x8270024
#endif


#define KIOU_HOOK_RVA_SET_TARGET_FRAMERATE                  0x6B718A4
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE                       0x5D379DC
#define KIOU_HOOK_RVA_NSS_SETSKILLEVEL                      0x5D37968
#define KIOU_HOOK_RVA_NSS_SEARCHFULL                        0x5D37A74
#define KIOU_HOOK_RVA_ACCOUNT_EXISTS                        0x5922CD0
#define KIOU_HOOK_RVA_LOGIN_ARGS_CREATE                     0x5B9DC04
#define KIOU_HOOK_RVA_REGISTER_USER_ARGS_CREATE             0x5B9DC94
#define KIOU_HOOK_RVA_RUN_LOGIN_SEQ_MOVENEXT                0x58152BC
#define KIOU_HOOK_RVA_GET_SELF_PROFILE_MOVENEXT             0x5BB99DC
#define KIOU_HOOK_RVA_HTTPMSGINVOKER_SEND_ASYNC             0x6082AC0
#define KIOU_HOOK_RVA_AI_END                                0x59EA720
#define KIOU_HOOK_RVA_CPUSTREAM_END                         0x59F15D4
#define KIOU_HOOK_RVA_LOCAL_END                             0x5A046B4
#define KIOU_HOOK_RVA_ONLINE_END                            0x5A06158
#define KIOU_HOOK_RVA_REPLAY_END                            0x5A30320
#define KIOU_HOOK_RVA_HEADER_PROVIDER_SET_OR_UPDATE_HEADER  0x5BD9EE8
#define KIOU_HOOK_RVA_SYNC_ITEM_LIST_MERGE                  0x5C3C29C
#define KIOU_HOOK_RVA_COLLECTION_PRESET_MERGE               0x5C458C4
#define KIOU_HOOK_RVA_SELECT_CHAR_ASYNC                     0x5CACEF8
#define KIOU_HOOK_RVA_SELECT_CHAR_REPLY_MERGE               0x5C2C034
#define KIOU_HOOK_RVA_MATCHING_PLAYER_MERGE                 0x5B51C3C
#define KIOU_HOOK_RVA_HISTORY_DETAIL_MERGE                  0x5C06590
#define KIOU_HOOK_RVA_HISTORY_GET_PREMIUM                   0x5C05FF0
#define KIOU_HOOK_RVA_KIFU_DETAIL_IS_PREMIUM                0x585E000
#define KIOU_HOOK_RVA_VOICE_PLAYER_SATISFIES                0x582E614
#define KIOU_HOOK_RVA_VOICE_CELL_GET_IS_LOCKED              0x584DB64
#define KIOU_HOOK_RVA_BSE_CTOR                              0x597E608
#define KIOU_HOOK_RVA_BSE_ENSURE_INITIALIZED                0x5980890
#define KIOU_HOOK_RVA_RBSUPPORT_GET_ENABLED                 0x5942AA0
#define KIOU_HOOK_RVA_RBSUPPORT_GET_DEPTH                   0x5942AC0
#define KIOU_HOOK_RVA_HOME_UTILITY_PRESENTER_CTOR           0x5AA4054
#define KIOU_HOOK_RVA_UIBUTTONBASE_ONPOINTERCLICK           0x5DD7F54
#define KIOU_HOOK_RVA_TITLE_SCENE_MOVENEXT                  0x5DD2874
#define KIOU_HOOK_RVA_GAME_ORCHESTRATOR_IS_AFK              0x594A034
#define KIOU_HOOK_RVA_BSE_EVALUATE_ASYNC                    0x5980304
#define KIOU_HOOK_RVA_MOVE_RESULT_CAN_USE_SPECIAL           0x5B54F68
#define KIOU_HOOK_RVA_MOVE_RESULT_FREE_REMAINING            0x5B54F38
#define KIOU_HOOK_RVA_MOVE_RESULT_TICKET_REMAINING          0x5B54F48
#define KIOU_HOOK_RVA_MP_FREE_REMAINING                     0x5B50DA4
#define KIOU_HOOK_RVA_MP_PAID_AVAILABLE                     0x5B50DB4
#define KIOU_HOOK_RVA_MATCH_GET_VALID_FOUND                 0x5D0A78C
#define KIOU_HOOK_RVA_MATCH_RECEIVE_TIMEOUT_MOVENEXT        0x5D0C408
#define KIOU_HOOK_RVA_MATCH_STREAM_ARGS_CREATE              0x5BCF8CC
#define KIOU_HOOK_RVA_MATCH_START_D3_MOVENEXT               0x5D0DA8C
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_SEND_ASYNC       0x5BD00E0
#define KIOU_HOOK_RVA_MATCH_STREAM_HANDLER_DISPOSE_ASYNC    0x5BCFEF4
#define KIOU_HOOK_RVA_MSG_EXT_TO_BYTE_ARRAY                 0x52C071C
#define KIOU_HOOK_RVA_MSG_EXT_WRITE_TO_BUFFER               0x52C0DB8
#define KIOU_HOOK_RVA_MSG_EXT_MERGE_FROM_ROSEQ              0x52C042C
#define KIOU_HOOK_RVA_MSG_PARSER_MERGE_FROM_CODED           0x52C1B18
#define KIOU_HOOK_RVA_NSS_SEARCH                            0x5D37A50
#define KIOU_HOOK_RVA_NSS_SEARCHMULTI                       0x5D383A4
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPV                     0x5D390A0
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIWITHPV                 0x5D3960C
#define KIOU_HOOK_RVA_NSS_SEARCHMULTIPVWITHPV               0x5D3A38C
#define KIOU_HOOK_RVA_NSS_SETOPTION                         0x5D37694
#define KIOU_HOOK_RVA_BACK_TO_TITLE_RUN_ASYNC               0x5CFC394
#define KIOU_HOOK_RVA_NSS_SETHASHSIZE_DIRECT                0x5D379DC
#define KIOU_HOOK_RVA_NSS_SETOPTION_DIRECT                  0x5D37694
#define KIOU_HOOK_RVA_GAMEOBJECT_GETCOMPONENT               0x6BD07F8
#define KIOU_HOOK_RVA_RTU_WORLDTOSCREENPOINT                0x6F2628C
#define KIOU_HOOK_RVA_JSON_FORMATTER_GET_DEFAULT            0x52ACC40
#define KIOU_HOOK_RVA_JSON_FORMATTER_FORMAT                 0x52AE828
#define KIOU_HOOK_RVA_GAMECTRL_GET_USI_TEXT                 0x5D49970
#define KIOU_HOOK_RVA_POSITION_TO_SFEN                      0x5D49C70
#define KIOU_HOOK_RVA_USIPARSER_PARSE_USI                   0x5D5CBB0
#define KIOU_HOOK_RVA_KIFWRITEOPTIONS_CTOR                  0x5D5925C
#define KIOU_HOOK_RVA_KIFWRITER_WRITE                       0x5D59264
#define KIOU_HOOK_RVA_RUN_RESET_USER_DATA_SEQ               0x5DCC204
#define KIOU_HOOK_RVA_RUN_DELETE_ACCOUNT_SEQ                0x5DCC2B4
