#!/usr/bin/env python3
"""Generate ``rva/kiou_rva_<ver>.h`` from a recipe and the dump index.

Every ``KIOU_HOOK_RVA_*`` macro the catalog in ``KIOUHook.m`` references
comes from one of two places:

  * a hook site — the address is already in ``recipes/v<ver>.py`` SITES,
    keyed by hook id, so it is copied verbatim (``check_recipes`` then
    enforces that the two never drift), or
  * a direct-ABI helper — not a hook site, so there is no recipe row. Those
    are resolved by the anchor names in ``DIRECT_ABI_ANCHORS`` below.

Usage:
    python3 -m tools.gen_rva_header --version 1.1.0 \\
        --index ../../assets/1.1.0/dump.cs.index.json

Run it once per supported version after porting a recipe; the output is
committed.
"""

from __future__ import annotations

import argparse
import importlib
import os
import pathlib
import re
import sys

from tools.check_recipes import (
    RECIPES_DIR,
    REPO_ROOT,
    RVA_DIR,
    _catalog_macro_by_hook_id,
    _find_sites_assign,
    _load_module_ast,
)

# Direct-ABI helpers: called straight through KIOUHookSiteAddr rather than
# hooked, so they carry hook_id = -1 in the catalog and never appear in a
# recipe. The anchor is the durable identity; the address is not.
DIRECT_ABI_ANCHORS: dict[str, str] = {
    "KIOU_HOOK_RVA_BACK_TO_TITLE_RUN_ASYNC":
        "Project.Orchestration.BackToTitleSequence.RunAsync(CancellationToken)",
    "KIOU_HOOK_RVA_NSS_SETHASHSIZE_DIRECT":
        "Rshogi.NativeSyncSession.SetHashSize(int)",
    "KIOU_HOOK_RVA_NSS_SETOPTION_DIRECT":
        "Rshogi.NativeSyncSession.SetOption(string, string)",
    "KIOU_HOOK_RVA_GAMEOBJECT_GETCOMPONENT":
        "UnityEngine.GameObject.GetComponent(string)",
    "KIOU_HOOK_RVA_RTU_WORLDTOSCREENPOINT":
        "UnityEngine.RectTransformUtility.WorldToScreenPoint(Camera, Vector3)",
    "KIOU_HOOK_RVA_JSON_FORMATTER_GET_DEFAULT":
        "Google.Protobuf.JsonFormatter.get_Default()",
    "KIOU_HOOK_RVA_JSON_FORMATTER_FORMAT":
        "Google.Protobuf.JsonFormatter.Format(IMessage)",
    "KIOU_HOOK_RVA_GAMECTRL_GET_USI_TEXT":
        "Project.ShogiCore.GameController.GetUSIText()",
    "KIOU_HOOK_RVA_POSITION_TO_SFEN":
        "Project.ShogiCore.Position.ToSFEN()",
    "KIOU_HOOK_RVA_USIPARSER_PARSE_USI":
        "Project.ShogiCore.USIParser.ParseUSI(string)",
    "KIOU_HOOK_RVA_KIFWRITEOPTIONS_CTOR":
        "Project.ShogiCore.KIFWriteOptions.ctor()",
    "KIOU_HOOK_RVA_KIFWRITER_WRITE":
        "Project.ShogiCore.KIFWriter.Write(RecordManager, KIFWriteOptions)",
    "KIOU_HOOK_RVA_RUN_RESET_USER_DATA_SEQ":
        "Project.Title.TitleMenuPopupPresenter.RunResetUserDataSequenceAsync(CancellationToken)",
    "KIOU_HOOK_RVA_RUN_DELETE_ACCOUNT_SEQ":
        "Project.Title.TitleMenuPopupPresenter.RunDeleteAccountSequenceAsync(CancellationToken)",
}

HEADER = """\
#pragma once

// ===========================================================================
// kiou_rva_{stem}.h — site addresses for KIOU {version} (CFBundleVersion {build}).
//
// GENERATED by tools/gen_rva_header.py from recipes/{module}.py and the
// direct-ABI anchors it carries. Do not hand-edit: fix the recipe (or the
// anchor) and regenerate. tools/check_recipes.py re-checks every hook-site
// value against the recipe on each run.
// ===========================================================================

#define KIOU_HOOK_OBSERVER_SLOT_RVA        0x{observer:08X}
#define KIOU_HOOK_ENTRY_SLOT_BASE_RVA      0x{entry:08X}

// CAVE_REGION[0] from recipes/{module}.py — the consumer's Makefile may
// override this, but the two must agree.
#ifndef KIOU_HOOK_CAVE_REGION_START
#define KIOU_HOOK_CAVE_REGION_START        0x{cave:X}
#endif
"""


def _macro_order() -> list[str]:
    """Macro emission order: hook sites in catalog order, then direct-ABI."""
    text = (REPO_ROOT / "KIOUHook.m").read_text()
    rows = re.findall(
        r"\{\s*KIOU_HOOK_NAME_\w+\s*,\s*(?:-1|KIOU_HOOK_ID_\w+)\s*,\s*(KIOU_HOOK_RVA_\w+)\s*\}",
        text,
    )
    seen: list[str] = []
    for macro in rows:
        if macro not in seen:
            seen.append(macro)
    return seen


def generate(version: str, index_path: str, build: int) -> str:
    from tools.verify_sites import (
        find_method,
        load_dump_index,
        split_label,
        types_by_name,
    )

    module = "v" + version.replace(".", "_")
    recipe = RECIPES_DIR / f"{module}.py"
    if not recipe.exists():
        raise SystemExit(f"error: no recipe at {recipe}")

    sites = _find_sites_assign(_load_module_ast(recipe))
    # Placeholder rows (rva None) reserve a cave for a method this build no
    # longer has; they fall through to the anchor lookup below, which will
    # correctly report them as unresolvable if nothing matches.
    by_hook_id = {row[2]: row[0] for row in sites if row[0] is not None}
    placeholders = {row[2] for row in sites if row[0] is None}
    catalog = _catalog_macro_by_hook_id()
    macro_by_hook_id = {hook_id: macro for hook_id, macro in catalog.items()}

    by_name = types_by_name(load_dump_index(index_path))

    values: dict[str, int] = {}
    for hook_id, rva in by_hook_id.items():
        macro = macro_by_hook_id.get(hook_id)
        if macro:
            values[macro] = rva

    # Hook sites a version's recipe omits still need an address for the
    # JB / jailed build, so fall back to resolving their anchor from the
    # canonical label from any other recipe. Labels can themselves be
    # version-specific (a compiler-generated state machine is d__36 on one
    # build and d__38 on the next), so every known spelling is tried.
    labels: dict[str, list[str]] = {}
    for other in [recipe, *RECIPES_DIR.glob("v*.py")]:
        for row in _find_sites_assign(_load_module_ast(other)):
            known = labels.setdefault(row[2], [])
            if row[4] not in known:
                known.append(row[4])

    unresolved: list[str] = []
    for hook_id, macro in macro_by_hook_id.items():
        if macro in values:
            continue
        candidates = labels.get(hook_id, [])
        if not candidates:
            unresolved.append(f"{macro} (no recipe row or label for {hook_id})")
            continue
        for label in candidates:
            type_name, method_name, params = split_label(label)
            hit = find_method(by_name, type_name, method_name, param_types=params)
            if hit is not None:
                values[macro] = int(hit[1]["rva"], 0)
                break
        else:
            if hook_id in placeholders:
                # The recipe already says this method is gone from the
                # build. Emit 0 so KIOUHookInstall refuses to hook it
                # rather than MSHookFunction-ing a stale address.
                values[macro] = 0
            else:
                unresolved.append(f"{macro} ({' | '.join(candidates)})")

    for macro, anchor in DIRECT_ABI_ANCHORS.items():
        type_name, method_name, params = split_label(anchor)
        hit = find_method(by_name, type_name, method_name, param_types=params)
        if hit is None:
            unresolved.append(f"{macro} ({anchor})")
        else:
            values[macro] = int(hit[1]["rva"], 0)

    if unresolved:
        raise SystemExit(
            "error: could not resolve on "
            + version
            + ":\n  "
            + "\n  ".join(unresolved)
        )

    sys.path.insert(0, str(REPO_ROOT))
    os.environ["TARGET_VERSION"] = version
    v = importlib.import_module(f"recipes.{module}")

    order = [m for m in _macro_order() if m in values]
    order += [m for m in DIRECT_ABI_ANCHORS if m not in order]
    width = max(len(m) for m in order) + 1

    body = HEADER.format(
        stem=module[1:],
        version=version,
        build=build,
        module=module,
        observer=v.HOOK_SLOT_RVA,
        entry=v.ENTRY_SLOT_BASE_RVA,
        cave=v.CAVE_REGION[0],
    )
    lines = [body, ""]
    lines += [f"#define {m:<{width}} 0x{values[m]:X}" for m in order]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Target version, e.g. 1.1.0")
    parser.add_argument("--build", required=True, type=int, help="CFBundleVersion")
    parser.add_argument("--index", required=True, help="dump.cs.index.json for it")
    parser.add_argument("--out", help="Output path (default: rva/kiou_rva_<ver>.h)")
    args = parser.parse_args()

    text = generate(args.version, args.index, args.build)
    out = pathlib.Path(
        args.out or RVA_DIR / f"kiou_rva_{args.version.replace('.', '_')}.h"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
